#ifndef __dialog_skript__
#define __dialog_skript__

/**
@file
Subclass of scriptedit, which is generated by wxFormBuilder.
*/

#include "script_dlg.h"

/** Implementing scriptedit */
class dlg_script : public scriptedit
{
public:
	/** Constructor */
	dlg_script( wxWindow* parent );
	void OnOk(wxCommandEvent &event);
	void OnLoadScript(wxCommandEvent& event);
	void OnSave(wxCommandEvent& event);
	void OnSaveAs(wxCommandEvent& event);
	void OnRunScript(wxCommandEvent& event);
	void OnFontChanged(wxFontPickerEvent &event);
};

#endif // __dialog_skript__
