#ifndef __dialog_objekte__
#define __dialog_objekte__

/**
@file
Subclass of ObjDlg, which is generated by wxFormBuilder.
*/
#include "main.h"
#include "objects_dlgs.h"

/** Implementing ObjDlg */
class dlg_obj : public ObjDlg
{
protected:
	// Handlers for ObjDlg events.
	void OnInitObjects( wxInitDialogEvent& event );
	void OnTreeSelChanged( wxTreeEvent& event );
	void OnClassToggle( wxCommandEvent& event );
	void OnDelClass( wxCommandEvent& event );
	void OnActionAdd( wxCommandEvent& event );
	void OnActionEdit( wxCommandEvent& event );
	void OnActionDelete( wxCommandEvent& event );
	void OnSceditor( wxCommandEvent& event );
	void OnPatternEdit( wxCommandEvent& event );
	void OnSendToScript( wxCommandEvent& event );
	void OnActionBeginLabelEdit( wxTreeEvent& event );
	void OnActionEndLabelEdit( wxTreeEvent& event );
	void OnItemSelected( wxListEvent& event );
	void OnAliasAdd( wxCommandEvent& event );
	void OnAliasEdit( wxCommandEvent& event );
	void OnAliasDelete( wxCommandEvent& event );
	void OnAliasOn( wxCommandEvent& event );
	void OnGroupOff( wxCommandEvent& event );
	void OnGroupDelete( wxCommandEvent& event );
	void OnGroupChanged( wxCommandEvent& event );
	void OnColourCheck( wxCommandEvent& event );
	void OnTriggerOn( wxCommandEvent& event );
	void OnHotkeyAdd( wxCommandEvent& event );
	void OnHotkeyEdit( wxCommandEvent& event );
	void OnHotkeyDelete( wxCommandEvent& event );
	void OnHkGroupDelete( wxCommandEvent& event );
	void OnHkGroupToggle( wxCommandEvent& event );
	void OnHkGroupChanged( wxCommandEvent& event );
	void OnHkOn( wxCommandEvent& event);
	void OnHkSelected( wxListEvent& event );
	void OnVarAdd( wxCommandEvent& event );
	void OnVarEdit( wxCommandEvent& event );
	void OnVarDelete( wxCommandEvent& event );
	void OnVarOn( wxCommandEvent& event );
	void OnVGroupDelete( wxCommandEvent& event );
	void OnVGroupOff( wxCommandEvent& event );
	void OnVGroupChanged( wxCommandEvent& event );
	void OnVarSelected( wxListEvent& event );
	void OnListAdd( wxCommandEvent& event );
	void OnListEdit( wxCommandEvent& event );
	void OnListDelete( wxCommandEvent& event );
	void OnListOn( wxCommandEvent& event );
	void OnAddItem( wxCommandEvent& event );
	void OnListGroupOff( wxCommandEvent& event );
	void OnDeleteListGroup( wxCommandEvent& event );
	void OnListSelected( wxListEvent& event );
	void OnLGroupChanged( wxCommandEvent& event );
	void OnTimerSelected( wxListEvent& event );
	void OnTimerAdd( wxCommandEvent& event );
	void OnTimerDelete( wxCommandEvent& event );
	void OnTimerEdit( wxCommandEvent& event );
	void OnTimerStart( wxCommandEvent& event );
	void OnTimerOn( wxCommandEvent& event );
	void OnTimerGroupOff( wxCommandEvent& event );
	void OnDeleteTimerGroup( wxCommandEvent& event );
	void OnTGroupChanged( wxCommandEvent& event );
	void OnPageChanged( wxNotebookEvent& event );
	void OnRegExpTest(wxCommandEvent& event);
	void OnGaugeTreeSelChanged( wxTreeEvent& event );
	void OnAddGauge(wxCommandEvent& event);
	void OnDelGauge(wxCommandEvent& event);
	void OnEditGauge(wxCommandEvent& event);
	void OnButtonSelChanged( wxTreeEvent& event );
	void OnButtonAdd(wxCommandEvent& event);
	void OnButtonDelete(wxCommandEvent& event);
	void OnButtonEdit(wxCommandEvent& event);
public:
	/** Constructor */
	dlg_obj( wxWindow* parent );

	wxWindow* GetActions() {return m_trigger;}
	wxWindow* GetAlias() {return m_alias;}
	wxWindow* GetHotkeys() {return m_hotkey;}
	void BuildTree();
	void BuildAlias();
	void BuildHotkeys();
	void BuildVars();
	void BuildLists();
	void BuildTimers();
	void BuildGaugeTree();
	void BuildButtons();
	void SetData(wxString s);
	void SetBoolData(bool b) {m_data=b;}
private:
	MudMainFrame *m_frame;
	int m_index;
	int m_hkindex;
	int m_vindex;
	int m_lindex;
	int m_tindex;
	long m_keycode;
	wxString m_key;
	static int m_page;
	bool m_data;
	wxString m_s;
	wxString m_oldactiongroup;
};

#endif // __dialog_objekte__
