#ifndef __dialog_verbinden__
#define __dialog_verbinden__

/**
@file
Subclass of connectdlg, which is generated by wxFormBuilder.
*/

#include "connect_dlg.h"

/** Implementing connectdlg */
class dlg_charconn : public connectdlg
{
protected:
	// Handlers for connectdlg events.
	void OnInit( wxInitDialogEvent& event );
	void OnItemSelected( wxListEvent& event );
	void OnItemActivate( wxListEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnEdit( wxCommandEvent& event );
	void OnDelete( wxCommandEvent& event );
	
public:
	/** Constructor */
	dlg_charconn( wxWindow* parent );
	void FillList();
	int GetLastSelection() {return m_lastselection;}
private:
	MudMainFrame *m_frame;
	int m_lastselection;
};

#endif // __dialog_verbinden__
