#ifndef __dialog_hostsimple__
#define __dialog_hostsimple__

/**
@file
Subclass of Connect, which is generated by wxFormBuilder.
*/

#include "dlg_hostsimple.h"

/** Implementing Connect */
class dlg_hostsimple : public Connect
{
public:
	/** Constructor */
	dlg_hostsimple( wxWindow* parent );
private:
	
	
};

#endif // __dialog_hostsimple__
