#ifndef __dialog_package__
#define __dialog_package__

/**
@file
Subclass of dlg_pkg, which is generated by wxFormBuilder.
*/

#include "dlg_pkg.h"

//// end generated include

/** Implementing dlg_pkg */
class pkg_dlg : public dlg_pkg
{
	protected:
		// Handlers for dlg_pkg events.
		void OnChoice( wxCommandEvent& event );
		void OnToggle( wxCommandEvent& event );
		void OnCheckAll( wxCommandEvent& event );
	public:
		/** Constructor */
		pkg_dlg( wxWindow* parent );
		wxFileName GetFile() {return m_pkgfile->GetFileName();}
		vector<wxString>* GetAlias() {return &m_alias;}
		vector<wxString>* GetTrigger() {return &m_trigger;}
		vector<wxString>* GetVars() {return &m_vars;}
		vector<wxString>* GetHks() {return &m_hks;}
		vector<wxString>* GetTimers() {return &m_timers;}
		vector<wxString>* GetLists() {return &m_lists;}
		vector<wxString>* GetButtons() {return &m_buttons;}
		vector<wxString>* GetGauges() {return &m_gauges;}
	private:
		MudMainFrame *m_frame;
		vector<wxString> m_vars;
		vector<wxString> m_alias;
		vector<wxString> m_trigger;
		vector<wxString> m_hks;
		vector<wxString> m_timers;
		vector<wxString> m_lists;
		vector<wxString> m_buttons;
		vector<wxString> m_gauges;
	//// end generated class members
	
};

#endif // __dialog_package__
